### ISSUE TITLE
Feature: Transaction IDs

### ISSUE THREAD

**Issue by rmt** [vmware-archive/salt-api#120]
An transaction ID that can be passed into a call provides an excellent way to track a call from the initial action through to all the individual sub-actions that occur.

For example, User X makes a request to reinstall a VM, which triggers a workflow that locates the VM's hypervisor (or cloud provider), clean up old certificates, removes the machine from monitoring, poweroff's the machine, wipe's storage volumes, starts it again, waits for it to install/boot & register itself, triggers node configuration/app install, and adds it to the monitoring system.  It would obviously be nice to see in the logs that each of these steps were part of the same transaction, triggered by User X.

**Comment by SmithSamuelM** [comment]
Great Idea!

**Comment by rmt** [comment]
I suspect this would benefit from support in Salt itself, since client-side logs are also quite useful when something goes wrong, especially since logging tools such as Splunk can support grouping disparate logs by a common field. My initial use-case would be a workflow engine or state machine implemented using the Salt API. The workflow would retain the transaction ID that instantiated it.

**Comment by SmithSamuelM** [comment]
Salt already has much of this functionality from the API perspective. Any "job" created by the client/api.py returns
the unique jobid for that job. All subsequent events generated by the event bus also carry that jobid in both the event tag and the event data. This is how Halite matches events to jobs in its event driven display. 

What is missing is more events for all stages of jobs and other tasks run by salt. 

What is also missing is the concept of a higher level tasks, i.e. more than a Job. So adding the ability to inject an identifier in order to associate multiple jobs or other events to a higher level task is a great idea as I said.

But at least for any current remote execution jobs on minions there is a unique jobid which serves the purpose of a transaction id.  And if logs are not including the jobid then they should.

**Comment by whiteinge** [comment]
I'm closing this here since this is more of a Salt-core discussion. If you file a ticket on Salt for injecting an identifier into a job, which is a great idea, please do add a cross-reference from here for posterity. :)
