### ISSUE TITLE
Salt-api dies with Bad file descriptor 

### ISSUE THREAD

**Issue by syphernl** [vmware-archive/salt-api#137]
I'm running the latest version of Salt-API in a screen with debug mode enabled, is being queried every minute and after a while (generally < 24 hours) the process just stops with:

```
Bad file descriptor (epoll.cpp:81)
```

Version info:

```
           Salt: 2014.1.0-905-gd62e6d5
         Python: 2.7.5+ (default, Sep 19 2013, 13:49:51)
         Jinja2: 2.7
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.5
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

@gissues:{"order":33.333333333333333,"status":"backlog"}

**Comment by whiteinge** [comment]
Is there a traceback associated with that error message? I suspect it's coming from ZeroMQ but it would be helpful to know where in Salt's code it's coming through.

**Comment by syphernl** [comment]
It doesn't give any traceback when this happens but it always dies after a command and a "Loaded pprint_out as virtual pprint" and the pprinted data (results of manage.status)

**Comment by jeremyrosenbaum** [comment]
I've seen this happen with the salt CLI tool as well, when it's outputting the job returns.  No stack trace, just the error message.  The job is publishing correctly and querying the JID later shows that all minions successfully got the job and sent their returns.  I am also running ZMQ 3.2.3.  

It appears to be fixed by https://github.com/zeromq/libzmq/pull/738/files (which is in ZMQ 3.2.5)
