### ISSUE TITLE
Did not find any netapi configurations

### ISSUE THREAD

**Issue by yujianglei** [vmware-archive/salt-api#174]
hello:
salt version:  salt 2016.3.3 (Boron)
salt-api:   salt-api 2016.3.3 (Boron)
# when I install  salt-api  on master,  there  is   some  errors.  follow logs:

2016-10-11 14:38:36,240 [salt.client.netapi][ERROR   ][29803] Did not find any netapi configurations, nothing to start
2016-10-11 14:43:16,684 [salt.client.netapi][ERROR   ][1057] Did not find any netapi configurations, nothing to start

**Comment by NightOnFire** [comment]
if anyone else runs into this make sure your `rest_cherrypy:` is in the salt master config and spelled correctly. The problem is its not picking up your configuration.

**Comment by itskenny0** [comment]
Had the same symptom and this took me a while to figure out:

/etc/salt/master.d is included like this:
```default_include: master.d/*.conf```

This means that if you put a config file in this folder, it will only be picked up if its filename ends in `.conf`.
I didn't expect that since /etc/salt/master doesn't have a `.conf` ending either.
