### ISSUE TITLE
Deprecate Flask netapi module

### ISSUE THREAD

**Issue by whiteinge** [vmware-archive/salt-api#20]
I believe it no longer works. It was largely written before the lowdata interface had been hashed out.

**Comment by whiteinge** [comment]
I jumped the gun here to avoid future confusion and pulled it out. It's available for reference in Git's history.

**Comment by s0undt3ch** [comment]
Is there any reason why cherrypy was adopted instead of flask? Do note that I'm not acquainted(yet) with salt-api so, I might be asking a stupid question... ;)

**Comment by thatch45** [comment]
Because cherrypy is awesome!
cherrypy fits the bill better, because we use the cherrypy server and it has a lot of components that fit our use case more. Also since the UI has ended up being much more javascript heavy, so we care more about communication and less about templates, cherrypy seems to be a much better fit here.
Ask @whiteinge too, he might have more insight here

**Comment by whiteinge** [comment]
Flask is a decent framework for sure. I opted for CherryPy because I felt it was a better fit for the content-type negotiation (sending YAML/JSON, receiving YAML/JSON with other formats being trivial to add), and also a better fit for the custom cookie/header-based sessions. CherryPy is a solid, very minimalist, and very REST-friendly framework that provides hooks into every level of request/response execution so adding the aforementioned customization was really a walk in the park -- I am very impressed with it. The rest_cherrypy module is more docs than code which is a testament to how easy it is to hook in tiny functions wherever needed.

**Comment by s0undt3ch** [comment]
More than flask, I love [werkzeug](http://werkzeug.pocoo.org/), and it's request/response is also hugely tweekable, even on it's headers. Flash is just a simpler overlay that tightens more stuff together.

Anyway, who am I to say anything on this project :)  I haven't used it(yet! I'll do some heavy usage soon), and I can't say why one lib in favor of another lib(since I can't contribute to this yet), etc.

It just shows you guys how much I love @mitsuhiko's code.
