### ISSUE TITLE
how can i use pkg.install with sources arg?

### ISSUE THREAD

**Issue by coolias** [vmware-archive/salt-api#74]
Hi, All
  I use this to test my pkg.install api:

curl -si http://localhost:8000 \
        -H "Accept: application/x-yaml" \
        -H "X-Auth-Token: 6a60432474d5ee935ea4254b8e30f10ade34ea14" \
        -d client=local \
        -d tgt='202.*' \
        -d fun='pkg.install' \
        -d arg='sources="[{\"httpd\": "salt://pkg/centos/6/x64/httpd-2.2.15-26.el6.centos.x86_64.rpm\"}]"'

but, output is wrong:
return:
- {202.hscloud.com: 'Missing arguments executing "pkg.install": ArgSpec(args=[''name'',
  ''refresh'', ''fromrepo'', ''skip_verify'', ''pkgs'', ''sources''], varargs=None,
  keywords=''kwargs'', defaults=(None, False, None, False, None, None))'}

how can i do it, thanks

**Comment by whiteinge** [comment]
Since that last arg is contained within single quotes you can pull much of that formatting out. Try this:

``` bash
-d arg='sources=[{"httpd": "salt://pkg/centos/6/x64/httpd-2.2.15-26.el6.centos.x86_64.rpm"}]'
```

**Comment by whiteinge** [comment]
A little more explanation:

Salt itself also receives arguments at the CLI as strings so Salt gets a string of the form 'arg=val' and splits on the '=' then tries to process the right-hand side as YAML -- no additional quoting necessary.

The docs that talk about the "sources" arg in the yum module are slightly misleading here since shell-quoting rules make it so that Salt sees both: `salt '*' pkg.install sources='[{"foo": "salt://foo.rpm"}'` and `salt '*' pkg.install 'sources=[{"foo": "salt://foo.rpm"}'` as identical. I prefer the latter since it's a better representation of what Salt is actually seeing as the argument.
