### ISSUE TITLE
running salt-api overwrites master pid file

### ISSUE THREAD

**Issue by craig5** [vmware-archive/salt-api#86]
We are trying to get the netapi working and made changes suggested here:

http://www.automationlogic.com/archives/427
https://salt-api.readthedocs.org/en/latest/topics/netapis/writing.html

However, when starting it seems to exit right away and the pid file for the master seems to have the pid for the (now defunct) salt-api command:

$ more salt/run/salt-master.pid  
8128

$ ps -fp 8128
UID        PID  PPID  C STIME TTY          TIME CMD
root      8128  2039  1 12:58 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-master

$ sudo /usr/bin/salt-api -l debug
[INFO    ] Configuration file path: /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Created pidfile: /export/apps/salt/run/salt-master.pid
[DEBUG   ] Chowned pidfile: /export/apps/salt/run/salt-master.pid to user: root
[DEBUG   ] loading netapi in ['/export/apps/salt/cache/extmods/netapi', '/usr/lib/python2.6/site-packages/saltapi/netapi']
[DEBUG   ] Skipping /export/apps/salt/cache/extmods/netapi, it is not a directory

$ more .../salt/run/salt-master.pid  
10638

$ ps -fp 10638
UID        PID  PPID  C STIME TTY          TIME CMD

$ ps -ef |grep salt-master
root      2039     1  0 Jan07 ?        00:00:00 runsv salt-master
root      8128  2039  0 12:58 ?        00:00:01 /usr/bin/python2.6 /usr/bin/salt-master
[snip]

**Comment by slai** [comment]
I ran into this problem as well but haven't had a chance to submit a pull request yet. The fix is simple - in saltapi/cli.py, comment out the following line in the run method:

self.process_config_dir()

That line causes the master configuration to be read again after it has already been merged with the API CLI configuration (with the appropriate parameters, like pidfile, skipped), replacing the correctly merged config with the purr master version.

Hopefully I'll get a chance to submit the pull request tonight.

**Comment by s0undt3ch** [comment]
@slai if you send a pull request with this fix, I'll close mine(#87) since you did found the fix.

**Comment by whiteinge** [comment]
Er. I missed that last comment before merging the req. Sorry!

@slai Thanks for the find. @s0undt3ch thanks for the pull req.

**Comment by slai** [comment]
Not a problem @s0undt3ch and @whiteinge. As you can see, I didn't get around to submitting it anyway last night!
